image: "rust:latest"

stages:
    - lint
    - test

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

lint:fmt:
    stage: lint
    before_script:
        - rustup component add rustfmt
    script: cargo fmt -- --check

lint:clippy:
    stage: lint
    before_script:
        - apt update -yqq
        - apt install -yqq --no-install-recommends clang libpq-dev
        - rustup component add clippy
    script: cargo clippy -- --deny warnings

lint:elephantry:
    stage: lint
    before_script:
          - rustup toolchain install nightly
          - apt update -yqq
          - apt install -yqq postgresql-common
          - /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          - apt install -yqq clang libpq-dev sudo postgresql-18
          - cargo install cargo-dylint dylint-link
          - echo "en_US UTF-8" > /etc/locale.gen
          - locale-gen en_US.UTF-8
          - sudo -u postgres pg_ctlcluster 18 main start
          - sudo -u postgres psql --command "create role root WITH LOGIN ENCRYPTED PASSWORD '1234' SUPERUSER;";
          - sudo -u postgres psql --command "create database root with owner root;";
          - export PGHOST=localhost PGPASSWORD=1234
    script: cargo dylint --git https://github.com/elephantry/lints --all

.test: &test
    stage: test
    before_script:
        - MODE=$(echo "$CI_JOB_NAME" | cut -d ':' -f 2)
        - apt update -yqq
        - apt install -yqq --no-install-recommends clang graphviz libpq-dev
    script: make test MODE=$MODE

test:debug:
    <<: *test

test:release:
    <<: *test

cache:
    paths:
        - $CARGO_HOME
        - target/
